name: OpenWrt-Widora

on:
  # release:
    # types: [published]
  watch:
    types: [started]  

jobs:
  build_openwrt:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Space cleanup
        env: 
          DEBIAN_FRONTEND: noninteractive
        run: |
            docker rmi `docker images -q`
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
            sudo -E apt-get update
            sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
            sudo -E apt-get -y autoremove --purge
            sudo -E apt-get clean

      - name: Clone source code
        env: 
          REPO_URL: https://github.com/Lienol/openwrt
          REPO_BRANCH: 19.07
        run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        
      - name: Adding a plug-in source
        run: |
          chmod +x ./extend.sh && ./extend.sh
       
      - name: Update & Install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a  
         
      - name: Generate configuration file
        env:
          CONFIG_FILE: 'widora.config'
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          cat Extend.config >> openwrt/.config
          cd openwrt && make defconfig
         
      - name: Make download
        working-directory: ./openwrt
        run: |
          make download -j$(nproc) 
        
      - name: Build firmware
        working-directory: ./openwrt      
        run: |               
          make -j$(nproc) || make -j1 V=s           
          
      - name : Upload artifact firmware
        uses: actions/upload-artifact@master     #上传
        with:        
          name: Widora_firmware       
          path: openwrt/bin/targets
          
      - name : Upload artifact Plug-in library
        uses: actions/upload-artifact@master
        with:
          name: Widora_ Plug-in        
          path: openwrt/bin/packages
          
