name: OpenWrt-rpi4

on:
  # release:
    # types: [published]
  # watch:
    # types: [started]  

jobs:
  build_openwrt:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Space cleanup
        env: 
          DEBIAN_FRONTEND: noninteractive
        run: |
            docker rmi `docker images -q`
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
            sudo -E apt-get update
            sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
            sudo -E apt-get -y autoremove --purge
            sudo -E apt-get clean
      - name: Clone source code
        env: 
          REPO_URL: https://github.com/coolsnowwolf/lede
          REPO_BRANCH: master
        run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

      - name: Update & Install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a  

      - name: Import external feeds
        working-directory: ./openwrt
        run: |
          git clone --depth 1 https://github.com/xiaorouji/openwrt-passwall package/lienol
         
      - name: Generate configuration file
        env:
          CONFIG_FILE: 'rpi4.config'
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x ./rpi4-wifi.sh && ./rpi4-wifi.sh
          cd openwrt && make defconfig
         
      - name: Make download
        working-directory: ./openwrt
        run: |
          make download -j$(nproc) 
        
      - name: Build firmware
        working-directory: ./openwrt      
        run: |               
          make -j$(nproc) || make -j1 V=s           
          
      - name : Upload artifact
        uses: actions/upload-artifact@master     #上传
        with:        
          name: OpenWrt_rpi4b2      
          path: openwrt/bin/targets
